### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by lapp0** [chaelim/ExcelRTD#2]
You appear to be using `excelRTDserver.py` from the `pywin32` repo. The mailing list suggests this no longer works

https://mail.python.org/pipermail/python-win32/2012-April/012207.html

**Comment by chaelim** [comment]
Thanks for the comment. This project is still under construction. I'll add more document with more examples. If you're using the recent Excel builds, for example Office 365 released in this year, it should work.

**Comment by lapp0** [comment]
I tried running with an excel build from this week.

```
PS C:\Users\andre\ExcelRTD\python> py stockrow_rtd.py --register
Requesting elevation and retrying...
Registered: STOCKROW
```

`Stockrow_rtd_demo.xlsx` is all `#N/A`.

Any idea what I'm missing?

**Comment by lapp0** [comment]
i ran it as administrator, same `#N/A` in the spreadsheet, but I don't get the `Requesting elevation`:

```
PS C:\Users\andre\ExcelRTD\python> py stockrow_rtd.py --register
Registered: STOCKROW
```

**Comment by chaelim** [comment]
Sorry for lack of the instruction. I just updated the readme file https://github.com/chaelim/ExcelRTD/blob/master/python/README.md. I think it's because the two DLL files (`pythoncom38.dll` and `pywintypes38.dll`) under the `<Your Python Installation Path>\Lib\site-packages\pywin32_system32` need to be under a folder added to the `PATH` environment variable.

**Comment by chaelim** [comment]
Please let me know if you still have trouble to run.

**Comment by lapp0** [comment]
I copied the 2 DLLs to python path, but I still get `#N/A`. Could you please advise?

![image](https://user-images.githubusercontent.com/2560255/89113994-c61f6680-d445-11ea-96b5-933f9bd42df8.png)

Path variable:
![image](https://user-images.githubusercontent.com/2560255/89114172-8a859c00-d447-11ea-8c31-b3a14e19189e.png)

![image](https://user-images.githubusercontent.com/2560255/89114199-ae48e200-d447-11ea-9e79-d7eb70629701.png)


![image](https://user-images.githubusercontent.com/2560255/89113956-5c06c180-d445-11ea-85c8-3b3dd2d50c58.png)

Something suspicious: the program ends with no error, it doesn't even stay alive to serve requests (or fail to serve requests). Is there an error in the program that's not being logged to STDERR? Why would this be?

**Comment by chaelim** [comment]
That seems odd. It's actually writing logs under logs folder "ExcelRTD\Python\logs". If there is any logs under that folder, please open the latest one and look at it. However, if it failed to load the "pythoncom38.dll" for somehow then the log file could be empty.

**Comment by lapp0** [comment]
Indeed, the log files are empty.

To be clear, you have this working and get live stock updates on your end, correct?

I wonder what it could be if my path is correct and contains the dll's.

Any other thoughts?

**Comment by chaelim** [comment]
Yes, it's working for me I verified it from multiple machines. But there still could be something missing in the instructions. Let's try couple of things.

First, let's test if pythoncom is working. Unzip "test_excel.py" from the attached `test_excel.zip` file below to your local folder. You can just unzip it to "ExcelRTD\Python" folder. You can look at the python code and this is copied from https://raw.githubusercontent.com/mhammond/pywin32/9fbc2ed3c0d69aca2475975a599cc316016599d3/com/win32com/test/testMSOffice.py and simplified.
Then run it from the command line `python test_excel.py` then it should launch Excel and create a test workbook.

[test_excel.zip](https://github.com/chaelim/ExcelRTD/files/5011635/test_excel.zip)

**Comment by chaelim** [comment]
By the way, if you added the new python folders to `PATH` environment variable, please make sure restart Excel program after exiting any existing instance.
And before running the `test_excel.py` above, you can type `where pythoncom38.dll` on the command line to make sure it's on the path.

**Comment by lapp0** [comment]
Thanks for your effort. Here are my results:

>Then run it from the command line python test_excel.py then it should launch Excel and create a test workbook.

```
PS C:\Users\andre\ExcelRTD> python3 .\test_excel.py
Starting Excel for Dynamic test...
.\test_excel.py:59: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  xl.Cells(6,2).Value = pythoncom.MakeTime(time.time())
```

>By the way, if you added the new python folders to PATH environment variable, please make sure restart Excel program after exiting any existing instance.

I've indeed tried restarting

>And before running the test_excel.py above, you can type where pythoncom38.dll on the command line to make sure it's on the path.

Good clue. It isn't in path. I'm not sure why though, it's within a directory in $Env:Path.

```
PS C:\Users\andre\ExcelRTD> $Env:Path
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Users\andre\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\andre\AppData\Local\Programs\Python\Python38\;C:\Users\andre\AppData\Local\Microsoft\WindowsApps;C:\Users\andre\.dotnet\tools
```
![image](https://user-images.githubusercontent.com/2560255/89115738-aa25c000-d459-11ea-99ef-efa9e524a341.png)


Thanks again for your help btw. I'm mostly familiar with linux dev, so this is new to me.

**Comment by chaelim** [comment]
I saw the `DeprecationWarning` as well. But did excel launch and created a test workbook? If it did, that means the pythoncom is working. I noticed you're using PS. This is result when run `where.exe pythoncom38.dll`

![image](https://user-images.githubusercontent.com/2214727/89116081-d4b94e00-d444-11ea-9eef-aeaa256b4fd8.png)

I'll be happy to make it work for you.

**Comment by chaelim** [comment]
This is on my machine. I'm using Windows 10 Version 1903.

![image](https://user-images.githubusercontent.com/2214727/89116183-ff57d680-d445-11ea-8b34-552c53c236d2.png)

**Comment by lapp0** [comment]
>But did excel launch and created a test workbook?

Yes, with a diagonal of "Hi" messages.

>where.exe

That was my mistake, I thought `where` alone worked per posix standard.

```
PS C:\Users\andre\ExcelRTD> where pythoncom38.dll
PS C:\Users\andre\ExcelRTD> where.exe pythoncom38.dll
C:\Users\andre\AppData\Local\Programs\Python\Python38\pythoncom38.dll
```

so I have pythoncom38.dll in my Path.

**Comment by chaelim** [comment]
I'm using `Python 3.8.5 (python-3.8.5-amd64.exe) + pywin32-228.win-amd64-py3.8.exe`. I remember older version of Python had some issue on loading the pythoncom38.dll from the excel.

**Comment by lapp0** [comment]
I am using 3.8.5 as well. I ran the `pywin32-228.win-amd64-py3.8.exe` installer a while ago in attempt to make it work.

I also can confirm that the program is successfully completing the line, however no additional logs seem to be produced.

`win32com.server.register.UseCommandLine(StockrowServer)`

**Comment by chaelim** [comment]
`get-childitem -Path Registry::"HKCR\CLSID\{1540C97E-BD8B-444E-9F18-B38FB33711E5}"`

![image](https://user-images.githubusercontent.com/2214727/89116396-8c039400-d448-11ea-944c-2977440416b5.png)

**Comment by lapp0** [comment]
I'll try coming up with a test case to see if it's excel failing or this script failing using `pyrtd` soon.

**Comment by lapp0** [comment]
```
PS C:\Users\andre\ExcelRTD\python> get-childitem -Path Registry::"HKCR\CLSID\{1540C97E-BD8B-444E-9F18-B38FB33711E5}"


    Hive: HKCR\CLSID\{1540C97E-BD8B-444E-9F18-B38FB33711E5}


Name                           Property
----                           --------
Debugging                      (default) : 0
Implemented Categories
InprocServer32                 (default)      : pythoncom38.dll
                               ThreadingModel : both
ProgID                         (default) : FINNHUB
PythonCOM                      (default) : finnhub_rtd.FinnhubServer
PythonCOMPath                  (default) : C:\Users\andre\ExcelRTD\python
```

**Comment by chaelim** [comment]
OK looks everything is same. Just in case there is any ghost Excel process. Run this `Stop-Process -Name excel`

**Comment by chaelim** [comment]
Previous one was FINNHUB RTD. This is for STOCKROW `get-childitem -Path Registry::"HKCR\CLSID\{C38E586E-C6B9-41B2-9C99-88180E2B9DB8}"`

![image](https://user-images.githubusercontent.com/2214727/89116454-2b288b80-d449-11ea-9975-d9b5c4959f10.png)

**Comment by lapp0** [comment]
```
PS C:\Users\andre\ExcelRTD\python> Stop-Process -Name excel
PS C:\Users\andre\ExcelRTD\python> get-childitem -Path Registry::"HKCR\CLSID\{C38E586E-C6B9-41B2-9C99-88180E2B9DB8}"


    Hive: HKCR\CLSID\{C38E586E-C6B9-41B2-9C99-88180E2B9DB8}


Name                           Property
----                           --------
Debugging                      (default) : 0
Implemented Categories
InprocServer32                 (default)      : pythoncom38.dll
                               ThreadingModel : both
ProgID                         (default) : STOCKROW
PythonCOM                      (default) : stockrow_rtd.StockrowServer
PythonCOMPath                  (default) : C:\Users\andre\ExcelRTD\python
```

**Comment by chaelim** [comment]
Please check if following option is checked. This should be unchecked to run RTD COM server.
`File menu  -> Options -> Trust Center -> Trust Settings -> Add-ins`
![image](https://user-images.githubusercontent.com/2214727/89116908-0a166980-d44e-11ea-99d2-a92971c5b904.png)

**Comment by lapp0** [comment]
Yes, it was unchecked. I do see the stockrow addin fwiw

![image](https://user-images.githubusercontent.com/2560255/89116999-21fae700-d468-11ea-90d0-6845d66f5254.png)

**Comment by lapp0** [comment]
I installed the ThinkOrSwim RTD to verify that Excel could indeed perform RTD functionality. 

![image](https://user-images.githubusercontent.com/2560255/89143846-f0daef00-d519-11ea-9b00-84ac09f9194d.png)

![image](https://user-images.githubusercontent.com/2560255/89144050-9f7f2f80-d51a-11ea-8fe2-51a451a88c87.png)


Please let me know if you have any other thoughts on things I should attempt.

I think my best bet right now is reinstall everything and try again.

Edit: extra question, do you have any idea why stockrow is included as an addin, while tos is not? It's a long shot, but thought this might be indicative of something going wrong
![image](https://user-images.githubusercontent.com/2560255/89144165-e8cf7f00-d51a-11ea-983f-1bf38aeddd8b.png)

**Comment by chaelim** [comment]
Here is my best guess. It's probably because Excel disabled the "stockrow" RTD due to load failure happened before. Please go to `File -> Excel Options -> Add-ins -> Select "Disabled Items" and hit "Go" button`. If you see the `stockrow` in the disabled item, please enable it. Then try the stockrow demo file again.

![image](https://user-images.githubusercontent.com/2214727/89359328-665dd100-d67a-11ea-8630-f982b56d218e.png)

**Comment by lapp0** [comment]
Nope, I have the same "There are no disabled items" message as you.

**Comment by lapp0** [comment]
If another user comes across this issue, I hope this is helpful. But I don't want to waste any more of your time with an issue that is only known to impact me right now. I think I'm going to try an alternative solution. Thanks for your help though.

**Comment by chaelim** [comment]
Hmm, and it shouldn't be on the Add-ins list. 
Run "regedit" and go to the following entry, if you see `stockrow` then delete it. I don't know if it'll fix the problem though.
`HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Excel\Add-in Manager`

**Comment by lapp0** [comment]
I don't have `/Add-in Manager` in the registry under Excel.
